public enum GameStage {

    Intro_Spawn,
    Intro_Greeting,
    Intro_TutorialTrapped,
    Intro_SlimeShowcase,
    Intro_CastleTease,
    Castle_FindHome,
    Castle_ForgotKey,
    Castle_FindKeyFight,
    Castle_Explore,
    Castle_SlimeHoard,
    Outburst_ExplainSlimes,
    Outburst_ChallengeGiven,
    Outburst_PortalTransit,
    Challenge_LabyrinthNav,
    Challenge_ObjectiveRoom,
    Challenge_BossRoom,
    GameEnd,

    HomeBase_Tut_Spawn,
    HomeBase_Tut_Entryway,
    HomeBase_Tut_Equipment,
    HomeBase_Tut_WeaponsMagic,
    HomeBase_Tut_Abilities,
    HomeBase_Tut_Combat,
    HomeBase_Tut_Kitchen,
    HomeBase_Tut_Office,
    HomeBase_Tut_Complete,
}